version: "3"
services:
  ds1-apache:
    container_name: ds1-apache
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  default:
    name: ds1-container-network
    external: true